"""Init

Revision ID: 582049c1e538
Revises: 1a529ad33638
Create Date: 2024-08-09 03:33:12.209590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582049c1e538'
down_revision: Union[str, None] = '1a529ad33638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('service_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'updated_at')
    op.drop_column('service_requests', 'created_at')
    # ### end Alembic commands ###
