"""Initial migration

Revision ID: 950452c59ac7
Revises: 455bce0dca0b
Create Date: 2024-08-08 15:01:40.075981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950452c59ac7'
down_revision: Union[str, None] = '455bce0dca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handymen', sa.Column('user_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('handymen', 'user_type')
    # ### end Alembic commands ###
