"""request migration

Revision ID: dfe97dd38578
Revises: 950452c59ac7
Create Date: 2024-08-08 21:17:13.660427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe97dd38578'
down_revision: Union[str, None] = '950452c59ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handymen', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('handymen', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('service_requests', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('service_requests', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'longitude')
    op.drop_column('service_requests', 'latitude')
    op.drop_column('handymen', 'longitude')
    op.drop_column('handymen', 'latitude')
    # ### end Alembic commands ###
